### ISSUE TITLE
Split layout with two tables shows a header row only on the first table.

### ISSUE THREAD

**Issue by ericbeland** [mare-imbrium/canis#6]
In a split layout with two tables, the colored header row on the 2nd table is missing. If you switch the order of the table, it will always show up on the first, one, but not the second.

layout.split(0.5, 0.5) do |top, bottom|
  top.component = table1
  bottom.component = table2
end

This behavior is observed on Mac with OS x Mojave and Ruby 2.4.1 (maybe elsewhere, but I have not tried yet).

**Comment by mare-imbrium** [comment]
1. Can you post a working file ?
2. Does this happen if you increase size of layout by 1 or change the table
size ?

Please give me a little time to look into this. Thanks.

**Comment by ericbeland** [comment]
I'll whip one up. I'll also try out changing the size. Thanks!

**Comment by ericbeland** [comment]
I created a gist with a reproduction here:

https://gist.github.com/ericbeland/abd29fa97d9ad1520312ad251d1b4ec0

Here is a link to what I see:

https://imgur.com/wLbjlVP

**Comment by mare-imbrium** [comment]
I have been looking at it and have some observations:
1. If i use `vsplit` then the table headers **do** get displayed.
2. If I use `split` with three splits, or change the percentage of the splits, only the first table shows its header, the rest **do not**.
3. If I use `suppress_headers: true` then the first data row will not print (or it is overwritten).

I am coming back to this code-base after several years and it will take me time to figure out where the issue lies. Is `Table` not printing, or is `Layout` overwriting the first row ? `Layout` is pretty new code.

I also looked at `examples/term2.rb` and it uses `Tabular` with stack and flow layout. Do you think this is useful for you ?  

I will continue to try to figure out the issue.

Another option is that rather than use `StackLayout`, try using `stack` as in `term2.rb` and use two tables inside (as you have done in your sample). I will make a sample for you and post it tomorrow, if you can wait 12 hours or so.

Thanks.

**Comment by ericbeland** [comment]
Sounds good. Those observations fit with my own. 

I can wait.  It's a very nice library, overall. Thanks for looking at it!  Best,

Eric

**Comment by mare-imbrium** [comment]
I have tried to use `term2.rb` but the same bug appears here, too. It would since `stack()` is just a wrapper to `StackLayout`.

I hope what you are developing is not critical. I say this because most ruby users are into webapps and very little of this library has been used. My own regular usage was simple tabular info, usually one table with a few fields.

That is why I stripped and simplified `canis` and made `umbra` which I now use. But even my usage of `umbra` is very limited to single tables. I don't think anyone else has used `umbra`. You may want to check `examples/extab2.rb` in `umbra` which uses tables inside boxes.

Please note that neither canis nor umbra are production-ready.

**Comment by mare-imbrium** [comment]
**UPDATE:**

I found that the bug is in `Table` and not `SplitLayout`. Basically, `Table` will print header only if `row` is 1. It will simply NOT print a header if `row` is more than 1 !!!

**Comment by mare-imbrium** [comment]
I have fixed the bug. It was in the `prefresh` call in `table.rb`. The first `prefresh` call for the header had values that only worked if the row was 0 or 1. 

Now it should work.  Thanks for your patience. 

I would recommend that you first check out the gem `ncumbra` (as repo `umbra`) which is a much simpler and smaller version of `canis`. It will be a lot easier to maintain going forward. `canis` is too large and complex. Hopefully, `umbra` will satisfy your requirements.

**Comment by ericbeland** [comment]
Awesome! Thanks so much!

I took a look at using an umbra implementation. It looks like it might also work for my use case, which is basically a horizontally split layout with 2 boxes on one side, and 3 on the other. It looks not too different from your example. It has 4 tables that dynamically update from polling a REST API. I am trying to figure out how to make resize work in umbra. I'd like to just re-draw the whole thing after the resize completes. For umbra, it seems like the latest is not pushed to github, so I had to link my gemfile to git.

**Comment by mare-imbrium** [comment]
I will check about pushing the latest to Umbra.
You can contact me about any issues you face there. I am not clear on what you are resizing. Or are you just dynamically updating a table ? I have an example of a thread that updates a table which I may not have put into git. I'll do that in a few hours, also.

**Comment by ericbeland** [comment]
I'm just dynamically updating tables, that's like 90% of my use-case. The only other thing i have is a "box" with our logo as ascii text in it.

The resize thing is just what to do when the terminal window is resized (which makes things look funny), I'd like to just reset/redraw everything like when it was first loaded.

**Comment by mare-imbrium** [comment]
There is a `RESIZE` event to which a block can be bound. This will trigger your method/block whenever the terminal is resized. There are a few examples that use `:RESIZE`.

    @form.bind(:RESIZE) {  resize }
